apiVersion: apps/v1
kind: Deployment
metadata:  
  name: nodejs-deployment  
  labels:    
    app: helloworld
spec:  
  replicas: 2  
  selector:    
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec: 
     containers:
      - name: helloworld
        image: patrah/myjsapp:v1.0.1
        ports:
        - containerPort: 8081

